apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-app-result-pod
      app: demo-voting-app
  template:
    metadata:
      name: voting-app-result-pod
      labels:
        name: voting-app-result-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app-result
          image: docker/example-voting-app-result
          ports:
            - containerPort: 80
