apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-app-worker-pod
      app: demo-voting-app
  template:
    metadata:
      name: voting-app-worker-pod
      labels:
        name: voting-app-worker-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app-worker
          image: docker/example-voting-app-worker
          ports:
            - containerPort: 80